### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by gavz** [allyshka/pwngitmanager#2]
Traceback (most recent call last):
  File "./pwngit.py", line 51, in <module>
    new.run()
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 727, in run
    getattr(executor, command[0])(command[1:])
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 406, in get
    self.__get(file, show)
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 438, in __get
    resp = self.__download(url_path)
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 546, in __download
    return get_url(url, "object ({0})".format(url), False, self.raw_cmd)
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 270, in get_url
    response = urllib.request.urlopen(url, timeout=15)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
Traceback (most recent call last):
  File "./pwngit.py", line 51, in <module>
    new.run()
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 727, in run
    getattr(executor, command[0])(command[1:])
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 406, in get
    self.__get(file, show)
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 438, in __get
    resp = self.__download(url_path)
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 546, in __download
    return get_url(url, "object ({0})".format(url), False, self.raw_cmd)
  File "/root/Documents/git_dump/pwngitmanager/gitlib.py", line 270, in get_url
    response = urllib.request.urlopen(url, timeout=15)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by allyshka** [comment]
Hello. Library cannot get answer from socket while specified time. Maybe you internet connection is through proxy, server is offline or index file is large and script stops execute by default timeout. I need more information about run parameters to recognize where problem is. If you can, please send me all script parameters you use I'll try to reproduce error. 
I'm add try ..except to catch this type of error. Thanks.
